### ISSUE TITLE
Add working run.sh script to run project

### ISSUE THREAD

**Issue by IJustDev** [IJustDev/numbers#1]
There is a file called `run.sh` in the latest commit. Currently without any effective content. Please create a script that will compile all classes of the main package into the `classes/` directory and run those class files afterwards.

**Comment by Shumyk** [comment]
#2 
Implemented run.sh and deleted compiled class files from VSC.

**Comment by Shumyk** [comment]
I guess this issue can be closed.

Also, I want to propose you to create new issue to add .gitignore file in order to not have IDE files committed and popping out all the time.

**Comment by IJustDev** [comment]
Already done. Implemented in upcoming commit. Thank you :)
CLOSING
